baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "landed"

[Params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Your name"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # Show sidebar at page. please select "left" or "right", default is "none".
  sidebar = "none"

  # 404 error customization
  [Params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [Params.navigation]
    title = "どうぶつ担当"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[Params.navigation.link]]
      name = "Home"
      url = "/"
    # Optional style as class attribute
    # class = "button special"

    [[Params.navigation.link]]
      name = "Layouts"
      url = "#"

      [[Params.navigation.link.child]]
        name = "Article"
        url = "article"

      [[Params.navigation.link.child]]
        name = "Submenu"
        url = "#"

        [[Params.navigation.link.child.child]]
          name = "Option 1"
          url = "#"

        [[Params.navigation.link.child.child]]
          name = "Option 2"
          url = "#"

        [[Params.navigation.link.child.child]]
          name = "Option 3"
          url = "#"

        [[Params.navigation.link.child.child]]
          name = "Option 4"
          url = "#"

    [[Params.navigation.link]]
      name = "Elements"
      url = "elements"

    [[Params.navigation.link]]
      name = "Sign Up"
      url = "#"
      class = "button special"

  # Banner section
  [Params.banner]
    title = "どうぶつ担当"
    description = """ネッコが好きだ！  
                イッヌが好きだ！
                """
    image = "/img/pic11.jpg"
    next = "#one"

  # Spotlight section
  [[Params.spotlight]]
    id = "one"
    style = "bottom"
    image = "/img/pic12.jpg"
    title = "ノルウェージャンフォレストキャット担当"
    description = "かわいい！"
    content1 = """ノルウェーからやってきたネッコ！"""
    content2 = """さむさにつよい！"""
    next = "#two"

  [[Params.spotlight]]
    id = "two"
    style = "right"
    image = "/img/pic13.jpg"
    title = "黒シッバ担当"
    description = "かわいい！"
    content = """くろくてまるい！"""
    next = "#three"

    [[Params.spotlight.link]]
      name = "Learn More"
      url = "#"
      style = "button"

  [[Params.spotlight]]
    id = "three"
    style = "left"
    image = "/img/pic14.jpg"
    title = "すーん担当"
    description = "かわいい！"
    content = """ねてるだけでかわいい！"""
    next = "#four"

    [[Params.spotlight.link]]
      name = "Learn More"
      url = "#"
      style = "button"

  [Params.box]
    style = "tile" # "tile" or "entry"
    id = "four"
    title = "Accumsan sed tempus adipiscing blandit"
    description = "Iaculis ac volutpat vis non enim gravida nisi faucibus posuere arcu consequat"

    [[Params.box.tile]]
      icon = "fa-area-chart"
      title = "Ipsum sed commodo"
      description = "Feugiat accumsan lorem eu ac lorem amet accumsan donec. Blandit orci porttitor."

    [[Params.box.tile]]
      icon = "fa-comment"
      title = "Eleifend lorem ornare"
      description = "Feugiat accumsan lorem eu ac lorem amet accumsan donec. Blandit orci porttitor."

    [[Params.box.tile]]
      icon = "fa-flask"
      title = "Cubilia cep lobortis"
      description = "Feugiat accumsan lorem eu ac lorem amet accumsan donec. Blandit orci porttitor."

    [[Params.box.tile]]
      icon = "fa-paper-plane"
      title = "Non semper interdum"
      description = "Feugiat accumsan lorem eu ac lorem amet accumsan donec. Blandit orci porttitor."

    [[Params.box.tile]]
      icon = "fa-file"
      title = "Odio laoreet accumsan"
      description = "Feugiat accumsan lorem eu ac lorem amet accumsan donec. Blandit orci porttitor."

    [[Params.box.tile]]
      icon = "fa-lock"
      title = "Massa arcu accumsan"
      description = "Feugiat accumsan lorem eu ac lorem amet accumsan donec. Blandit orci porttitor."

    [[Params.box.link]]
      name = "Magna sed feugiat"
      url = "#"
      style = "button"

  [Params.mailform]
    id = "five"
    title = "Magna faucibus lorem diam"
    description = "Ante metus praesent faucibus ante integer id accumsan eleifend"
    url = "#"
    text = "Get Started"

  # Footer section
  [Params.footer]
    enable = true
    copyright = "Company Name"

    # Uses font awesome icons
    [[Params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com"
      label = "Twitter"

    [[Params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com"
      label = "Facebook"

    [[Params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com"
      label = "LinkedIn"

    [[Params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com"
      label = "Instagram"
    
    [[Params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com"
      label = "GitHub"

    [[Params.footer.social]]
      icon = "fa-envelope"
      url= "#"
      label = "Email"

    [[Params.footer.quicklinks]]
      content = "Design: "
      url= "https://www.html5up.net"
      label = "HTML5 UP"
